apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-duration-api
  labels:
    app: trip-duration-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trip-duration-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: trip-duration-api
    spec:
      containers:
      - name: trip-duration-api
        image: ${DOCKER_REGISTRY}/trip-duration-api:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc