- name: Create Kubernetes Cluster
  hosts: localhost
  become: false
  vars:
    cluster_name: "{{ cluster_name | default('ml-pipeline-cluster') }}"

  tasks:
    - name: Check for required dependencies
      command: "which {{ item }}"
      register: dependency_check
      ignore_errors: true
      changed_when: false
      loop:
        - minikube
        - kubectl

    - name: Check if minikube cluster exists
      shell: "minikube status -p {{ cluster_name }}"
      register: cluster_status
      ignore_errors: true
      changed_when: false

    - name: Create minikube cluster
      command: >
        minikube start
        --driver=docker
        --cpus=4
        --memory=2200mb
        --profile={{ cluster_name }}
        --addons=dashboard,ingress,metrics-server
      when: cluster_status.rc != 0

    - name: Get kubeconfig from minikube
      shell: "minikube update-context -p {{ cluster_name }} && cat ~/.kube/config"
      register: kubeconfig_content

    - name: Save kubeconfig to file
      copy:
        content: "{{ kubeconfig_content.stdout }}"
        dest: "{{ playbook_dir }}/../kubeconfig"
        mode: '0600'

    - name: Verify cluster is running
      shell: kubectl --kubeconfig={{ playbook_dir }}/../kubeconfig get nodes
      register: node_status
      retries: 10
      delay: 5
      until: node_status.rc == 0

    - name: Display cluster information
      debug:
        msg: "Kubernetes cluster '{{ cluster_name }}' created successfully!"
